# Generated by Django 6.0.2 on 2026-02-25 16:36

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerypage',
            name='sections',
            field=wagtail.fields.StreamField([('month', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.PageChooserBlock', (), {'page_type': ['gallery.ArtworkPage']}), 2: ('wagtail.blocks.StructBlock', [[('artwork', 1)]], {}), 3: ('wagtail.blocks.ListBlock', (2,), {}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('artworks', 3)]], {})}),
        ),
    ]
