# Generated by Django 6.0.2 on 2026-03-11 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_gallerypage_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkpage',
            name='suggested_count',
            field=models.IntegerField(default=3, help_text='Number of artworks to suggest'),
        ),
    ]
