# Generated by Django 6.0.2 on 2026-03-08 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_gif'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='gif',
        ),
    ]
