# Generated by Django 6.0.2 on 2026-03-22 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_homepage_cta_link_homepage_cta_text_and_more'),
        ('wagtailcore', '0096_referenceindex_referenceindex_source_object_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cta_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page that opens on clicking CTA button'),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page that opens on clicking hero image'),
        ),
    ]
