# Generated by Django 6.0.2 on 2026-03-22 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_homepage_cta_link_alter_homepage_hero_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='cta_text',
            field=models.CharField(default='Enter Hange Gallery', help_text='Text to display on the CTA button', max_length=50, verbose_name='CTA button text'),
        ),
    ]
