# Generated by Django 6.0.2 on 2026-03-08 15:26

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='content',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
