# Generated by Django 6.0.2 on 2026-03-09 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_aboutpage_from_address_aboutpage_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='from_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='to_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
