# Generated by Django 6.0.2 on 2026-03-22 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_aboutpage_from_address_alter_aboutpage_subject_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='modal_button_text',
            field=models.CharField(blank=True, default='Want a custom artwork? I do commissions too!', max_length=255, verbose_name='Modal Trigger Button Text'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='use_modal_form',
            field=models.BooleanField(default=False, verbose_name='Open form in a modal?'),
        ),
    ]
