# Generated by Django 6.0.2 on 2026-03-23 12:29

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_aboutpage_thank_you_image'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutpage',
            old_name='thank_you_image',
            new_name='success_image',
        ),
        migrations.RenameField(
            model_name='aboutpage',
            old_name='thank_you_text',
            new_name='success_text',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='error_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='error_text',
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
