# Generated by Django 6.0.2 on 2026-03-23 12:30

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_rename_thank_you_image_aboutpage_success_image_and_more'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='error_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='error_text',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='success_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='success_text',
            field=wagtail.fields.RichTextField(),
        ),
    ]
