# Generated by Django 6.0.2 on 2026-03-23 13:13

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0009_remove_aboutpage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='modal_button_text',
            field=models.CharField(blank=True, default='Want a custom artwork? I do commissions too!', max_length=255, verbose_name='Modal Trigger Button Text'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='use_modal_form',
            field=models.BooleanField(default=False, verbose_name='Open form in a modal?'),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='error_text',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='from_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='success_text',
            field=wagtail.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='to_address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
